name: football_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  carousel_slider: ^4.1.1
  icons_plus:
  mysql1: ^0.20.0
  http: ^1.2.1
  flutter_secure_storage: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - google_fonts/
    - assets/images/
    - assets/

  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: google_fonts/TitilliumWeb-Regular.ttf
        - asset: google_fonts/TitilliumWeb-SemiBold.ttf
          weight: 700
        - asset: google_fonts/TitilliumWeb-SemiBold.ttf
          weight: 500
